services:
  web:
    container_name: insta-clone-frontend
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8000/api}
    image: projeto-final/frontend
    ports:
      - "3000:80"
    restart: unless-stopped
